services:
  djangoapp:
    container_name: library-api
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env.dev
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:14-alpine
    env_file:
      - .env.dev
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
  